name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate release
        run: >
          git archive --format=tar.gz --prefix=themes/ HEAD:themes/ -o themes.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: themes.tar.gz
